### ISSUE TITLE
Support for M7CL

### ISSUE THREAD

**Issue by airbenich** [MeestorX/companion-module-yamaha-MIDI#1]
Hi Andrew!

when i see that correctly, you are NOT using the SCP protocol for the communication, but the MIDI over TCP/IP protocol which is IMHO not documented by Yamaha.

Would it be possible to use this module also for the Yamaha M7CL (M7CL only has MID and not SCP)?
Did you have a brief idea if and what changes needs to be made in order to make it work with the M7CL?

When this module is used, can you connect in parallel with the iPad app to a mixing console or can only one midi connection be made?

Thank you for your help & work!
Greetings,
Vivian

**Comment by MeestorX** [comment]
M7CL uses a proprietary MIDI over TCP protocol that would need the Yamaha DME driver on the mixer, and then the module would need to speak "true" MIDI to the driver for it to work. I don't think Companion has a true MIDI driver, but that seems odd, maybe they do...
Anyway, there's very little documentation for the M7CL communication so it would take considerable work on my end to put that together, even if we could get around the lack of "true" TCP communication that the M7CL and LS9 suffer from.
Is this really important to you? If you were willing to put together a bounty for it, I could check into it. But, the M7 and LS are pretty old now and most people have upgraded to a QL or CL, so I'm not sure how much interest there would be...

**Comment by airbenich** [comment]
Thank you Andrew for your fast answer and your will to go into that topic deeply.
Unfortunately I have no budget for a bounty here. The only budget is my own manpower.

I will investigate then for myself. Maybe a pure MIDI control is also a way to steer some functions of the M7.
Do you know, if I can use the MIDI Port on the Board & use the iPad App (with uses MIDI over TCP) at the same time?

Thank you and greetings!
Vivian
